### ISSUE TITLE
Mulit Project Setup

### ISSUE THREAD

**Issue by eyedol** [ajoberstar/gradle-git#103]
I have a multi-project setup at https://github.com/eyedol/birudo. Using `v1.1.0-milestone.1` of this plugin doesn't include compiled classes for one of the modules, `core` in this setup. Any import of any class in the `core` module made by the `data` module leads to class not found exception causing the project not to get compiled. I had to downgrade to `v0.13.0` before my project compiled successfully. Any version above that leads to compile failure. 

I did a github comparison between [`v.0.13.0` and `v1.0.0-rc.1`](https://github.com/ajoberstar/gradle-git/compare/v0.13.0...v1.0.0-rc.1) for anything obvious but there were a lot of dependencies upgrades in `v1.0.0-rc.1 ` so not sure where the issue might be coming from. I suspected this [line](https://github.com/ajoberstar/gradle-git/compare/v0.13.0...v1.0.0-rc.1#diff-e221cda23063ccfea7f94735a3ccba16R71).

I added the `release` block in the root of the project; [`birudo/mobile`](https://github.com/eyedol/birudo/blob/master/birudo/mobile/build.gradle#L112). Is this a bug or I'm doing something obviously wrong?

**Comment by ajoberstar** [comment]
Just looking at your release block, I don't see anything wrong with your config. What is the error message (and stack trace) you were getting?

**Comment by eyedol** [comment]
Is a long one.

```
[git:master:C]± ./gradlew clean build --stacktrace
Inferred project: mobile, version: 0.1.0-milestone.1.dev.0.uncommitted+2b29257
:core:clean
:data:clean
:birudo:mobile:clean UP-TO-DATE
:birudo:tv:clean UP-TO-DATE
:birudo:wear:clean UP-TO-DATE
:core:compileJava
:core:processResources UP-TO-DATE
:core:classes
:core:jar
:core:assemble
:core:compileTestJava UP-TO-DATE
:core:processTestResources UP-TO-DATE
:core:testClasses UP-TO-DATE
:core:test UP-TO-DATE
:core:check UP-TO-DATE
:core:build
:data:compileLint
:data:copyDebugLint UP-TO-DATE
:data:preBuild UP-TO-DATE
:data:preDebugBuild UP-TO-DATE
:data:checkDebugManifest
:data:preDebugAndroidTestBuild UP-TO-DATE
:data:preReleaseBuild UP-TO-DATE
:data:prepareComAndroidSupportSupportV42100Library
:data:prepareComGoogleAndroidGmsPlayServicesBase6587Library
:data:prepareDebugDependencies
:data:compileDebugAidl
:data:compileDebugRenderscript
:data:generateDebugBuildConfig
:data:generateDebugAssets UP-TO-DATE
:data:mergeDebugAssets
:data:generateDebugResValues UP-TO-DATE
:data:generateDebugResources
:data:mergeDebugResources
:data:processDebugManifest
:data:processDebugResources
:data:generateDebugSources
:data:compileDebugJava

../Birudo/data/src/main/java/org/addhen/birudo/data/entity/mapper/JenkinsBuildInfoEntityMapper.java:63: error: unexpected type
        List<JenkinsBuildInfo> buildInfoList = new ArrayList<>();
                                                            ^
  required: class
  found:    <E>ArrayList<E>
  where E is a type-variable:
    E extends Object declared in class ArrayList
../Birudo/data/src/main/java/org/addhen/birudo/data/net/JenkinsClient.java:106: error: cannot find symbol
        GcmRegistrationStatus status = new GcmRegistrationStatus();
        ^
  symbol:   class GcmRegistrationStatus
  location: class JenkinsClient
../Birudo/data/src/main/java/org/addhen/birudo/data/net/JenkinsClient.java:106: error: cannot find symbol
        GcmRegistrationStatus status = new GcmRegistrationStatus();
                                           ^
  symbol:   class GcmRegistrationStatus
  location: class JenkinsClient
Note: ../Birudo/data/src/main/java/org/addhen/birudo/data/database/converter/EnumEntityFieldConverter.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
75 errors
:data:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':data:compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':data:compileDebugJava'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:44)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:97)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:158)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:138)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:92)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:235)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:222)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 47 more


BUILD FAILED

Total time: 18.133 secs

```

**Comment by eyedol** [comment]
Was the stacktrace useful? Let me know if you need more info.

**Comment by ajoberstar** [comment]
I just had a chance to look at it. It's really surprising to me that this plugin (and particularly those changes you linked to) would cause a compile failure. I'm not familiar with the other plugins you are using, so I can't say if there's some type of compatibility issue between those and gradle-git.

As you noted, the most likely suspect is probably the version being set on all projects. Do you know if your code (or the plugins you use) depend on any specific version being set (or not set)? That seems unusual, but I can't imagine what would cause this.

**Comment by eyedol** [comment]
Oh okay. I'll play around with my plugins to see what might be causing the issue. Thanks for the feedback

**Comment by eyedol** [comment]
Just like I suspected, changing my local build of this plugin with this [line](https://github.com/ajoberstar/gradle-git/compare/v0.13.0...v1.0.0-rc.1#diff-e221cda23063ccfea7f94735a3ccba16L71), gets this issue resolved for me. What other issues will it create if this change is merged into this repo?

**Comment by ajoberstar** [comment]
Undoing that change would be a revert of #91. Given that the version is inferred from the repo, I think it still makes sense for the default behavior to by applying the version to all projects within the build.

Making a leap that the Android plugins also make use of the `project.version` field, applying `release-opinion` after them may be overwriting something they need to function.

Perhaps moving the apply statement for `release-opinion`  and the `release {}` config to the root `build.gradle` would ensure it is applied first (and allow Android to overwrite as needed).

I think the only change I might want to make is printing a warning if a project's `version` property is already populated when `release-base` sets it.
