### ISSUE TITLE
Is there any good documentation on setting up gradle build to use ssh for authentication

### ISSUE THREAD

**Issue by dlethin** [ajoberstar/gradle-git#114]
I have a simple build that looks like this --

```
apply plugin: 'org.ajoberstar.release-opinion'

import org.ajoberstar.grgit.Grgit
import org.ajoberstar.gradle.git.release.opinion.Strategies

release {
  // need to specify the repository to interact with
  grgit = Grgit.open(project.file('.'))

  // need to override default strategy
  defaultVersionStrategy = Strategies.SNAPSHOT
}

task printVersion << {
        println "version is ${version}"
}
```

When I try to perform the release task, I get an error unable to authenticate:

```
gradle --stacktrace -Prelease.scope=major -Prelease.stage=rc release

...

Caused by: org.eclipse.jgit.api.errors.TransportException: git@myrepo.git: Auth fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:76)
	at java_util_concurrent_Callable$call$12.call(Unknown Source)
	at org.ajoberstar.grgit.operation.FetchOp.call(FetchOp.groovy:97)
	... 67 more
Caused by: org.eclipse.jgit.errors.TransportException: git@myrepo.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 70 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 77 more
```

I have no problem performing git on the command line and authenticating to the remote server and pushing tags for example, but its not working through GrGit/jgit.

Are there any clues or sample configuration you can point me to which shows me how to enable my build to use my default ~/.ssh/id_rsa key?

The doc for gradle-git authentications points to grgit AuthConfig javadoc page, but its not obvious what I'm supposed to do or how to wire it up in my gradle build.    I'm not having much luck googling a solution but will keep hacking away.

Thanks.

Doug

**Comment by dlethin** [comment]
I'm even more confused because I tried this and it worked --

```
gradle -Prelease.scope=major -Prelease.stage=rc release -Dorg.ajoberstar.grgit.auth.force=hardcoded
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
You are running the build with the Intuit Payments QBMS Gradle distribution
:prepare
:release
Inferred project: gradle-version-demo1, version: 1.0.0-rc.3
Tagging repository as v1.0.0-rc.3
Pushing changes in [refs/heads/master, v1.0.0-rc.3] to origin

BUILD SUCCESSFUL


```

No where did I specify my username/password in system properties or env variables, so I don't know why this is working.   But when I try to force it to 'sshagent' it fails with above error.

**Comment by ajoberstar** [comment]
There's a lot of weird stuff going on in JGit auth (and in my code too), and I don't claim to understand all of the finer points. I think the best starting point would be if you could provide `--debug` logs from the `force=hardcoded` attempt and the attempt without any of the `*.auth.*` properties set.

That should at the very least help me narrow down what code path it's using in each situation.

Shooting in the dark, I'm curious if your SSH key is password protected. If it's not, it's likely that Jsch never even asks for any further credentials, allowing the hardcoded option to work just fine. I've had some other reports of issues with ssh-agent and/or pageant that sometimes trace down to differences on their system. Hardcoded would bypass those entirely.

**Comment by ajoberstar** [comment]
If you get a chance to gather those debug logs, please reopen this issue and I can look into it more.
