### ISSUE TITLE
IOException triggered by JGit in gradle-git

### ISSUE THREAD

**Issue by sschuberth** [ajoberstar/gradle-git#116]
I'm setting up some Git configuration and hooks as part of our build system. Recently I ran across an IOException on a Windows PC where the native "git.exe" is not in PATH. In the line

    def grgit = org.ajoberstar.grgit.Grgit.open(rootDir)

I'm getting

    Caught exception in FS.readPipe()
    java.io.IOException: Cannot run program "bash" (in directory "C:\Users\sebastian"): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at java.lang.Runtime.exec(Runtime.java:617)
        at org.eclipse.jgit.util.FS.readPipe(FS.java:431)
        at org.eclipse.jgit.util.FS_Win32.discoverGitPrefix(FS_Win32.java:113)
        at org.eclipse.jgit.util.FS.gitPrefix(FS.java:517)
        at org.eclipse.jgit.util.SystemReader$Default.openSystemConfig(SystemReader.java:92)
        at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:171)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:577)
        at org.eclipse.jgit.api.Git.open(Git.java:113)
        at org.eclipse.jgit.api.Git.open(Git.java:97)
        at org.eclipse.jgit.api.Git$open.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy:59)
        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy)
        at java_util_concurrent_Callable$call.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:88)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.ajoberstar.grgit.Grgit.open(Grgit.groovy:209)
        at org.ajoberstar.grgit.Grgit.open(Grgit.groovy)
        at org.ajoberstar.grgit.Grgit$open.call(Unknown Source)

Judging from JGit's source code what seems to happen is:

FS_Win32.discoverGitPrefix() tries to determine the $prefix to the path where the system Git config is stored. On Windows, that would be the Git Installation directory under $ProgramFiles. So JGit tries to find git.exe (or git.cmd) in a directory in PATH to use that directory to determine the $prefix. If git.exe / git.cmd is not in PATH, JGit also tries to unconditionally call "bash" to run "which git" just in
case "git.exe" is only in PATH in the MSYS environment that Git for Windows ships with. But if "bash" itself is not in path the above exception is thrown.

I've fixed the part that JGit unconditionally calls "bash" without first checking it to be in PATH in [1]. However, as I see it that exception should have never been thrown in the first place as JGit wraps the exec() call within FS.readPipe() in a try / catch block for an IOException.

So my question is, why is the IOException thrown in the context of gradle-git? Are you doing something special in the use of JGit so that it does not catch exceptions?

[1] https://git.eclipse.org/r/#/c/47025/

**Comment by ajoberstar** [comment]
There's not really any magic going on from a JGit perspective. Particularly during the [OpenOp](https://github.com/ajoberstar/grgit/blob/master/src/main/groovy/org/ajoberstar/grgit/operation/OpenOp.groovy) it's just calling JGit's `Git.open()`. Can you reproduce this calling that method, without gradle-git or grgit involved?

**Comment by sschuberth** [comment]
I did not try to reproduce this without grgit, but I think I finally know what's going on: JGit 3.7 accidentally logs this IOException as an error, which seems to re-throw the exception. Logging as an error [is already fixed](https://bugs.eclipse.org/bugs/show_bug.cgi?id=459319), but there's not JGit release with that fix yet.

Anyway, it's not a gradle-git issue, so I'll be closing this.
