### ISSUE TITLE
Applying the 'release-opinion' on a new git-repository results in NullPointerException

### ISSUE THREAD

**Issue by hierynomus** [ajoberstar/gradle-git#153]
When applying the `release-opinion` (version=1.4.0-rc.1) plugin on a git project that has no tags set yet, the RebuildVersionStrategy throws a NullPointerException.

```
Caused by: java.lang.NullPointerException: Cannot invoke method status() on null object
        at org.ajoberstar.gradle.git.release.semver.RebuildVersionStrategy.selector(RebuildVersionStrategy.groovy:52)
        at org.ajoberstar.gradle.git.release.base.VersionStrategy$selector$0.call(Unknown Source)
        at org.ajoberstar.gradle.git.release.base.ReleasePluginExtension$_DelayedVersion_infer_closure1.doCall(ReleasePluginExtension.groovy:105)
        at org.ajoberstar.gradle.git.release.base.ReleasePluginExtension$DelayedVersion.infer(ReleasePluginExtension.groovy:104)
        at org.ajoberstar.gradle.git.release.base.ReleasePluginExtension$DelayedVersion.toString(ReleasePluginExtension.groovy:123)
        at org.gradle.api.internal.artifacts.ProjectBackedModule.getVersion(ProjectBackedModule.java:38)
 ```

**Comment by hierynomus** [comment]
Forgot to add Grgit.open(..) my bad.
