### ISSUE TITLE
github-pages 1.4.1 broken

### ISSUE THREAD

**Issue by ieugen** [ajoberstar/gradle-git#158]
Hello,

It seems github-pages plugin is broken in 1.4.2. I reverted to 1.3.2 which seems to work. 

The problem is that I get *Caused by: org.eclipse.jgit.api.errors.RefAlreadyExistsException: already exists* when trying to push a website.

My config: 

````
plugins {
  id 'org.ajoberstar.github-pages' version '1.4.1'
}
githubPages {
  repoUri = 'git@github.com:ieugen/ieugen.ro.git'
  pages {
    from 'output'
  }
}
````
The error:
````
Caused by: org.ajoberstar.grgit.exception.GrgitException: Problem checking out.
	at org.ajoberstar.grgit.operation.CheckoutOp.call(CheckoutOp.groovy:115)
	at org.ajoberstar.grgit.operation.CheckoutOp.call(CheckoutOp.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
	at org.ajoberstar.grgit.Grgit.methodMissing(Grgit.groovy:188)
	at org.ajoberstar.gradle.git.ghpages.GithubPagesPlugin$_createPrepareTask_closure1_closure4.doCall(GithubPagesPlugin.groovy:69)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 68 more
Caused by: org.eclipse.jgit.api.errors.RefAlreadyExistsException: already exists
	at org.eclipse.jgit.api.CheckoutCommand.processOptions(CheckoutCommand.java:497)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:202)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:126)
	at java_util_concurrent_Callable$call$0.call(Unknown Source)
	at org.ajoberstar.grgit.operation.CheckoutOp.call(CheckoutOp.groovy:112)
	... 78 more
````

**Comment by ajoberstar** [comment]
Can you give 1.4.2-rc.1 a try?

**Comment by ieugen** [comment]
Still does not work: 

````
Caused by: groovy.lang.MissingPropertyException: Could not find property 'repo' on task ':prepareGhPages'.
	at org.gradle.api.internal.AbstractDynamicObject.propertyMissingException(AbstractDynamicObject.java:43)
	at org.gradle.api.internal.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:35)
	at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:97)
	at org.gradle.api.tasks.Copy_Decorated.getProperty(Unknown Source)
	at org.ajoberstar.gradle.git.ghpages.GithubPagesPlugin$_createPublishTask_closure2_closure7.doCall(GithubPagesPlugin.groovy:91)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 68 more
````

**Comment by ieugen** [comment]
Looks ok. It seemed to be an issue with my setup. Maybe gradle build daemon.

**Comment by ajoberstar** [comment]
Cool, I'll get that released tonight.
