### ISSUE TITLE
Authentication failed in a gitlab-ci build

### ISSUE THREAD

**Issue by dodocat** [ajoberstar/gradle-git#177]
```
./gradlew release -Prelease.stage=final
```

I checked the stacktrace it seems gradle git use a wrong remote url missing token.
the correct remote url is something like: `http://gitlab-ci-token:blahblabla@git.dream/dawn/QAccount.git`
Url pint in stacktrace is `http://gitlab-ci-token@git.dream/dawn/QAccount.git`

```
19:12:18.459 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':QAccount:prepare'
19:12:18.460 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':QAccount:prepare' is up-to-date
19:12:18.460 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':QAccount:prepare' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
19:12:18.460 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':QAccount:prepare'.
19:12:18.461 [INFO] [org.gradle.api.Task] Fetching changes from remote: origin
19:12:18.482 [INFO] [org.ajoberstar.grgit.auth.TransportOpUtil] The following authentication options are allowed (though they may not be available): [PAGEANT, SSHAGENT, INTERACTIVE, HARDCODED]
19:12:18.524 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@34d3409d8 pairs: {GET /dawn/QAccount.git/info/refs?service=git-upload-pack HTTP/1.1: null}{Accept-Encoding: gzip}{Pragma: no-cache}{User-Agent: JGit/4.1.1.201511131810-r}{Accept: application/x-git-upload-pack-advertisement, */*}{Cache-Control: no-cache}{Host: git.dream}{Connection: keep-alive}
19:12:18.536 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@1673234011 pairs: {null: HTTP/1.1 401 Unauthorized}{Server: nginx}{Date: Fri, 20 May 2016 11:12:08 GMT}{Content-Type: text/plain}{Content-Length: 0}{Connection: keep-alive}{Cache-Control: no-cache}{Status: 401 Unauthorized}{WWW-Authenticate: Basic realm=""}{X-Request-Id: 8dcb6ed8-7369-4b99-ad83-75eaa484b054}{X-Runtime: 0.008758}
19:12:18.559 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':QAccount:prepare'
19:12:18.560 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :QAccount:prepare FAILED
19:12:18.563 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :QAccount:prepare (Thread[main,5,main]) completed. Took 0.105 secs.
19:12:18.563 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 0.105 secs, idle: 0.001 secs
19:12:18.568 [ERROR] [org.gradle.BuildExceptionReporter]
19:12:18.569 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
19:12:18.569 [ERROR] [org.gradle.BuildExceptionReporter]
19:12:18.569 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
19:12:18.569 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':QAccount:prepare'.
19:12:18.570 [ERROR] [org.gradle.BuildExceptionReporter] > Problem fetching from remote.
19:12:18.570 [ERROR] [org.gradle.BuildExceptionReporter]
19:12:18.570 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
19:12:18.571 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':QAccount:prepare'.
19:12:18.571 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
19:12:18.571 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
19:12:18.571 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
19:12:18.571 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
19:12:18.572 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
19:12:18.572 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
19:12:18.572 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
19:12:18.572 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
19:12:18.572 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
19:12:18.572 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
19:12:18.572 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
19:12:18.573 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
19:12:18.573 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
19:12:18.573 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
19:12:18.573 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
19:12:18.573 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
19:12:18.573 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
19:12:18.573 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
19:12:18.573 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
19:12:18.574 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
19:12:18.574 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
19:12:18.574 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
19:12:18.574 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
19:12:18.574 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Factories$1.create(Factories.java:22)
19:12:18.574 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
19:12:18.574 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
19:12:18.574 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
19:12:18.575 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
19:12:18.575 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
19:12:18.575 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
19:12:18.575 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
19:12:18.575 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
19:12:18.575 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
19:12:18.575 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
19:12:18.575 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
19:12:18.575 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
19:12:18.576 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
19:12:18.576 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
19:12:18.576 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
19:12:18.576 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
19:12:18.576 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
19:12:18.576 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
19:12:18.576 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
19:12:18.576 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
19:12:18.577 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
19:12:18.577 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
19:12:18.577 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
19:12:18.577 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
19:12:18.577 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
19:12:18.577 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
19:12:18.577 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
19:12:18.577 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
19:12:18.577 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
19:12:18.578 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.Main.doAction(Main.java:33)
19:12:18.578 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
19:12:18.578 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
19:12:18.578 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
19:12:18.578 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
19:12:18.578 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
19:12:18.578 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
19:12:18.578 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
19:12:18.578 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.ajoberstar.grgit.exception.GrgitException: Problem fetching from remote.
19:12:18.579 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.ajoberstar.grgit.operation.FetchOp.call(FetchOp.groovy:100)
19:12:18.579 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.ajoberstar.grgit.operation.FetchOp.call(FetchOp.groovy)
19:12:18.579 [ERROR] [org.gradle.BuildExceptionReporter] 	at java_util_concurrent_Callable$call.call(Unknown Source)
19:12:18.579 [ERROR] [org.gradle.BuildExceptionReporter] 	at java_util_concurrent_Callable$call.call(Unknown Source)
19:12:18.579 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
19:12:18.579 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.ajoberstar.grgit.Grgit.methodMissing(Grgit.groovy:188)
19:12:18.579 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.ajoberstar.gradle.git.release.base.BaseReleasePlugin$_addPrepareTask_closure2_closure5.doCall(BaseReleasePlugin.groovy:58)
19:12:18.579 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
19:12:18.579 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
19:12:18.579 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
19:12:18.580 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
19:12:18.580 [ERROR] [org.gradle.BuildExceptionReporter] 	... 60 more
19:12:18.580 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.eclipse.jgit.api.errors.TransportException: http://gitlab-ci-token@git.dream/dawn/QAccount.git: Authentication is required but no CredentialsProvider has been registered
19:12:18.580 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
19:12:18.580 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:76)
19:12:18.580 [ERROR] [org.gradle.BuildExceptionReporter] 	at java_util_concurrent_Callable$call$0.call(Unknown Source)
19:12:18.580 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.ajoberstar.grgit.operation.FetchOp.call(FetchOp.groovy:97)
19:12:18.580 [ERROR] [org.gradle.BuildExceptionReporter] 	... 70 more
19:12:18.580 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.eclipse.jgit.errors.TransportException: http://gitlab-ci-token@git.dream/dawn/QAccount.git: Authentication is required but no CredentialsProvider has been registered
19:12:18.581 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:492)
19:12:18.581 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:296)
19:12:18.581 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
19:12:18.581 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
19:12:18.581 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
19:12:18.581 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)

▽
        debug {
19:12:18.581 [ERROR] [org.gradle.BuildExceptionReporter] 	... 73 more
19:12:18.581 [ERROR] [org.gradle.BuildExceptionReporter]
19:12:18.581 [LIFECYCLE] [org.gradle.BuildResultLogger]
19:12:18.582 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
19:12:18.582 [LIFECYCLE] [org.gradle.BuildResultLogger]
19:12:18.582 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 5.178 secs
```

**Comment by ajoberstar** [comment]
This is a limitation of JGit, as noted in ajoberstar/grgit#46.
