### ISSUE TITLE
don't fail build during plugin application when no .git directory is available

### ISSUE THREAD

**Issue by lbergelson** [ajoberstar/gradle-git#205]
Currently, if there is no .git directory available it seems like grgit fails during plugin applications.

./gradlew compileJava

...

An exception occurred applying plugin request [id: 'org.ajoberstar.grgit', version: '1.5.1']
> Failed to apply plugin [id 'org.ajoberstar.grgit']
   > One of setGitDir or setWorkTree must be called.
This causes problems for distributing source separately from git. Could this be changed to fail lazily only when commands are invoked rather than when the plugin is applied? That way targets that don't rely on git could still run.

( this ticket was originally posted here https://github.com/ajoberstar/grgit/issues/120 )

**Comment by lbergelson** [comment]
Thank you!

**Comment by linqcan** [comment]
@ajoberstar 
Sorry for waking an old bug, but I do not think this change works as intended anymore. I get the following stacktrace:
```
Caused by: java.lang.IllegalArgumentException: One of setGitDir or setWorkTree must be called.
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.requireGitDirOrWorkTree(BaseRepositoryBuilder.java:590)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.setup(BaseRepositoryBuilder.java:555)
        at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:92)
        at org.eclipse.jgit.storage.file.FileRepositoryBuilder$build.call(Unknown Source)
        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy:95)
        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy)
        at java_util_concurrent_Callable$call.call(Unknown Source)
        at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
        at org.ajoberstar.grgit.Grgit$__clinit__closure1.doCall(Grgit.groovy:193)
        at org.ajoberstar.gradle.git.base.GrgitPlugin.apply(GrgitPlugin.groovy:34)
        at org.ajoberstar.gradle.git.base.GrgitPlugin.apply(GrgitPlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139)
        ... 73 more
```
Seems like "IllegalArgumentException" should be caught as well?(https://github.com/eclipse/jgit/blob/v4.5.0.201609210915-r/org.eclipse.jgit/src/org/eclipse/jgit/lib/BaseRepositoryBuilder.java#L555)

build.gradle:
```
apply plugin: "org.ajoberstar.grgit"

task hello() {
    doLast {
        println "Hello from ${project.name}"
    }
}
```

Should I file a new issue for this?

**Comment by ajoberstar** [comment]
See #228 and ajoberstar/grgit#128. This is fixed in grgit [1.7.1](https://github.com/ajoberstar/grgit/releases/tag/v1.7.1). I still need to make a gradle-git release that depends on that version.

As a workaround you can change your classpath dependency on grgit to that version.

**Comment by linqcan** [comment]
Ah, thanks for the quick reply! :smile: 
Will try your workaround!

**Comment by dapp** [comment]
I'm still having this issues with Grgit 1.7.1

**Comment by ajoberstar** [comment]
@dapp please post your full error output if you are still encountering this issue.
