### ISSUE TITLE
Execution failed for task ':prepare'.

### ISSUE THREAD

**Issue by philbert** [ajoberstar/gradle-git#220]
I'm trying to get the release-opinion plugin working on my project but it's failing with the error below.

This is the top of my build.gradle
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        'org.ajoberstar:gradle-git:1.5.1'
    }
}

apply plugin: 'org.ajoberstar.release-opinion'
apply plugin: 'org.ajoberstar.grgit'
```
I'm running Cygwin on Windows 7
```
./gradlew --version

------------------------------------------------------------
Gradle 3.0
------------------------------------------------------------

Build time:   2016-08-15 13:15:01 UTC
Revision:     ad76ba00f59ecb287bd3c037bd25fc3df13ca558

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.7.0_79 (Oracle Corporation 24.79-b02)
OS:           Windows 7 6.1 amd64
```

Here is the output from ./gradlew release --debug
```
16:47:36.714 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':prepare'
16:47:36.714 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':prepare' is up-to-date
16:47:36.715 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':prepare' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
16:47:36.715 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':prepare'.
16:47:36.715 [INFO] [org.gradle.api.Task] Fetching changes from remote: origin
16:47:36.716 [INFO] [org.ajoberstar.grgit.auth.TransportOpUtil] The following authentication options are allowed (though they may not be available): [PAGEANT, SSHAGENT, HARDCODED, INTERACTIVE]
16:47:36.716 [INFO] [org.ajoberstar.grgit.auth.TransportOpUtil] using interactive credentials, if needed
16:47:36.727 [INFO] [org.ajoberstar.grgit.auth.JschAgentProxySessionFactory] NetCat USocketFactory could not be configured: netcat does not support -U option.
16:47:36.737 [DEBUG] [org.ajoberstar.grgit.auth.JschAgentProxySessionFactory] NetCat USocketFactory failure details
com.jcraft.jsch.agentproxy.AgentProxyException: netcat does not support -U option.
        at com.jcraft.jsch.agentproxy.usocket.NCUSocketFactory.<init>(NCUSocketFactory.java:70)
        at sun.reflect.GeneratedConstructorAccessor447.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:239)
        at org.ajoberstar.grgit.auth.JschAgentProxySessionFactory$_closure4.doCall(JschAgentProxySessionFactory.groovy:171)
        at org.ajoberstar.grgit.auth.JschAgentProxySessionFactory$_closure4.doCall(JschAgentProxySessionFactory.groovy)
        at sun.reflect.GeneratedMethodAccessor1088.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at org.ajoberstar.grgit.auth.JschAgentProxySessionFactory$_determineUSocketFactory_closure7.doCall(JschAgentProxySessionFactory.groovy:151)
        at sun.reflect.GeneratedMethodAccessor949.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:430)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.findResult(DefaultGroovyMethods.java:3973)
        at org.codehaus.groovy.runtime.dgm$213.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.ajoberstar.grgit.auth.JschAgentProxySessionFactory.determineUSocketFactory(JschAgentProxySessionFactory.groovy:150)
...
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
16:54:39.208 [INFO] [org.ajoberstar.grgit.auth.JschAgentProxySessionFactory] ssh-agent available
16:54:39.209 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':prepare'
16:54:39.209 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :prepare FAILED
16:54:39.209 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :prepare (Thread[Daemon worker Thread 29,5,main]) completed. Took 0.027 secs.
16:54:39.210 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Worker root.1 completed (0 in use)
16:54:39.210 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 29,5,main]] finished, busy: 0.027 secs, idle: 0.002 secs
16:54:39.214 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
16:54:39.215 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
16:54:39.215 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
16:54:39.215 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
16:54:39.215 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':prepare'.
16:54:39.216 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not initialize class com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary
16:54:39.216 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
16:54:39.216 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
16:54:39.216 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
16:54:39.217 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
16:54:39.218 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
16:54:39.219 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
16:54:39.219 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 4.06 secs

```

**Comment by philbert** [comment]
Forgot I needed to search for 'nc' and not 'netcat' in the cygwin installer.
