### ISSUE TITLE
Performing the initial release fails with org.eclipse.jgit.api.errors.RefAlreadyExistsException

### ISSUE THREAD

**Issue by MartinAhrer** [ajoberstar/gradle-git#251]
Running the following plugin setup:
 
```
plugins {
    id 'org.ajoberstar.grgit' version '1.7.0'
    id 'org.ajoberstar.release-opinion' version '1.7.0'
}
```

A Jenkins pipeline build is issuing `./gradlew --no-daemon --quiet -Prelease.scope=patch -Prelease.stage=milestone  --debug --stacktrace release` and fails complaining with a `RefAlreadyExistsException`. 
No tags exist at that moment, Jenkins does a clean checkout and is working on a detached HEAD.

So the question is: is it required to put an inital tag manually before running a release? Locally I can run the same release command without any troubles. And subsequently releases run by the Jenkins job now work without troubles.

 
More exeception details below:

```
07:31:50.636 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
07:31:50.636 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
07:31:50.637 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
07:31:50.637 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
07:31:50.637 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
07:31:50.638 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
07:31:50.638 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.ajoberstar.grgit.exception.GrgitException: Problem creating tag.
07:31:50.638 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.ajoberstar.grgit.operation.TagAddOp.call(TagAddOp.groovy:122)
07:31:50.639 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.ajoberstar.grgit.operation.TagAddOp.call(TagAddOp.groovy)
07:31:50.639 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java_util_concurrent_Callable$call.call(Unknown Source)
07:31:50.639 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java_util_concurrent_Callable$call.call(Unknown Source)
07:31:50.639 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
07:31:50.640 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.ajoberstar.grgit.service.TagService.methodMissing(TagService.groovy:52)
07:31:50.640 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.ajoberstar.gradle.git.release.base.TagStrategy.maybeCreateTag(TagStrategy.groovy:81)
07:31:50.640 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.ajoberstar.gradle.git.release.base.TagStrategy$maybeCreateTag.call(Unknown Source)
07:31:50.641 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.ajoberstar.gradle.git.release.base.BaseReleasePlugin$_addReleaseTask_closure4_closure6.doCall(BaseReleasePlugin.groovy:90)
07:31:50.641 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:596)
07:31:50.642 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:577)
07:31:50.642 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
07:31:50.642 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
07:31:50.643 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 62 more
07:31:50.643 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.eclipse.jgit.api.errors.RefAlreadyExistsException: tag 'Tag={
07:31:50.643 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] object 6a10be6f48ae7f7b4d664849354ffc1c23442c5b
07:31:50.644 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] type commit
07:31:50.644 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] tag v0.0.1-milestone.1
07:31:50.64407:31:50.676 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess]  [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] tagger PersonIdent[root, root@7b80a7af7887, Thu Mar 30 07:31:50 2017 +0000]
07:31:50.644Releasing file lock for task history cache (/project/.gradle/3.4.1/taskHistory) [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 

07:31:50.677 [07:31:50.645DEBUG] [org.gradle.cache.internal.DefaultFileLockManager]  [Releasing lock on task history cache (/project/.gradle/3.4.1/taskHistory).
ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Release of 0.0.1-milestone.1
```

**Comment by ajoberstar** [comment]
I haven't seen that occur before, I wouldn't expect an error like that unless that tag definitely existed already. Can you post your build file? I'm curious if the tag strategy is modified at all, particularly `toTagString` or `parseTag`.

**Comment by MartinAhrer** [comment]
The tag strategy is not modified. However, I have reviewed the Jenkins setup. I had used the 'Clean before checkout' Git  behaviour which states:
> Clean up the workspace before every checkout by deleting all untracked files and directories, including those which are specified in .gitignore. It also resets all tracked files to their versioned state. This ensures that the workspace is in the same state as **if you cloned and checked out in a brand-new empty directory**, and ensures that your build is not affected by the files generated by the previous build.

It looks like this is not entirely true. After fully wiping out the project the tags were gone. Sorry for the false alert.
