### ISSUE TITLE
Teamcity configuration

### ISSUE THREAD

**Issue by nitink0bn** [ajoberstar/gradle-git#261]
I applied this plugin. The build was successful locally but I am having a problem while building in a Teamcity. It is not able to find gGrit in my build.gradle file. How to fix this?

**Comment by ajoberstar** [comment]
Could you provide more information on the failure you're seeing? 

- What version of Gradle?
- What version of gradle-git?
- What is the output of your build (preferably with `--stacktrace`)?

**Comment by nitink0bn** [comment]
Gradle Version : 3.3
Gradle-Git Version : 1.7.2
Stack Trace:-
Exception is:
[09:42:51][Gradle failure report] org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'abcd'.
[09:42:51][Gradle failure report] at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
[09:42:51][Gradle failure report] at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:176)
[09:42:51][Gradle failure report] at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
[09:42:51][Gradle failure report] at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:181)
[09:42:51][Gradle failure report] at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
[09:42:51][Gradle failure report] at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
[09:42:51][Gradle failure report] at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
[09:42:51][Gradle failure report] at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
[09:42:51][Gradle failure report] at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
[09:42:51][Gradle failure report] at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
[09:42:51][Gradle failure report] at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
[09:42:51][Gradle failure report] at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
[09:42:51][Gradle failure report] at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
[09:42:51][Gradle failure report] at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
[09:42:51][Gradle failure report] at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
[09:42:51][Gradle failure report] at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
[09:42:51][Gradle failure report] at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129)
[09:42:51][Gradle failure report] at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
[09:42:51][Gradle failure report] at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
[09:42:51][Gradle failure report] at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
[09:42:51][Gradle failure report] at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:161)
[09:42:51][Gradle failure report] at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:158)
[09:42:51][Gradle failure report] at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
[09:42:51][Gradle failure report] at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
[09:42:51][Gradle failure report] at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
[09:42:51][Gradle failure report] at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158)
[09:42:51][Gradle failure report] at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
[09:42:51][Gradle failure report] at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
[09:42:51][Gradle failure report] at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
[09:42:51][Gradle failure report] at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
[09:42:51][Gradle failure report] at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
[09:42:51][Gradle failure report] at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
[09:42:51][Gradle failure report] at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
[09:42:51][Gradle failure report] at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
[09:42:51][Gradle failure report] at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
[09:42:51][Gradle failure report] at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
[09:42:51][Gradle failure report] at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
[09:42:51][Gradle failure report] at org.gradle.util.Swapper.swap(Swapper.java:38)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
[09:42:51][Gradle failure report] at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
[09:42:51][Gradle failure report] at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
[09:42:51][Gradle failure report] at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
[09:42:51][Gradle failure report] Caused by: java.io.FileNotFoundException: /opt/tooling/CI/TeamCity/buildAgent/work/5e6f914cf839e43e/config (Is a directory)
[09:42:51][Gradle failure report] at org.eclipse.jgit.util.IO.readFully(IO.java:141)
[09:42:51][Gradle failure report] at org.eclipse.jgit.util.IO.readFully(IO.java:81)
[09:42:51][Gradle failure report] at org.eclipse.jgit.storage.file.FileBasedConfig.load(FileBasedConfig.java:141)
[09:42:51][Gradle failure report] at org.eclipse.jgit.lib.BaseRepositoryBuilder.loadConfig(BaseRepositoryBuilder.java:685)
[09:42:51][Gradle failure report] at org.eclipse.jgit.lib.BaseRepositoryBuilder.getConfig(BaseRepositoryBuilder.java:662)
[09:42:51][Gradle failure report] at org.eclipse.jgit.lib.BaseRepositoryBuilder.guessWorkTreeOrFail(BaseRepositoryBuilder.java:698)
[09:42:51][Gradle failure report] at org.eclipse.jgit.lib.BaseRepositoryBuilder.setupWorkTree(BaseRepositoryBuilder.java:628)
[09:42:51][Gradle failure report] at org.eclipse.jgit.lib.BaseRepositoryBuilder.setup(BaseRepositoryBuilder.java:557)
[09:42:51][Gradle failure report] at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:580)
[09:42:51][Gradle failure report] at org.eclipse.jgit.api.Git.open(Git.java:117)
[09:42:51][Gradle failure report] at org.eclipse.jgit.api.Git.open(Git.java:99)
[09:42:51][Gradle failure report] at org.eclipse.jgit.api.Git$open.call(Unknown Source)
[09:42:51][Gradle failure report] at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy:85)
[09:42:51][Gradle failure report] at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy)
[09:42:51][Gradle failure report] at java_util_concurrent_Callable$call.call(Unknown Source)
[09:42:51][Gradle failure report] at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
[09:42:51][Gradle failure report] at org.ajoberstar.grgit.Grgit$__clinit__closure1.doCall(Grgit.groovy:194)
[09:42:51][Gradle failure report] at build_3iw9d7tbewgkmyp55jwzayot5$_run_closure3.doCall(/opt/tooling/CI/TeamCity/buildAgent/work/5e6f914cf839e43e/build.gradle:31)
[09:42:51][Gradle failure report] at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
[09:42:51][Gradle failure report] at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
[09:42:51][Gradle failure report] at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:136)
[09:42:51][Gradle failure report] at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:528)
[09:42:51][Gradle failure report] at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:78)
[09:42:51][Gradle failure report] at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:104)
[09:42:51][Gradle failure report] at org.gradle.api.internal.DefaultNamedDomainObjectCollection$ContainerElementsDynamicObject.invokeMethod(DefaultNamedDomainObjectCollection.java:370)
[09:42:51][Gradle failure report] at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
[09:42:51][Gradle failure report] at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
[09:42:51][Gradle failure report] at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
[09:42:51][Gradle failure report] at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:83)
[09:42:51][Gradle failure report] at build_3iw9d7tbewgkmyp55jwzayot5.run(/opt/tooling/CI/TeamCity/buildAgent/work/5e6f914cf839e43e/build.gradle:25)
[09:42:51][Gradle failure report] at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)

**Comment by ajoberstar** [comment]
It seems like it's trying to read this as a file: `/opt/tooling/CI/TeamCity/buildAgent/work/5e6f914cf839e43e/config`. What directory is your `build.gradle` in?

**Comment by nitink0bn** [comment]
Issue Resolved. It's the issue with the team city configuration .
Thank you for your reply.
