### ISSUE TITLE
Unable to resolve class org.ajoberstar.grgit.Grgit

### ISSUE THREAD

**Issue by rajasekharpenti** [ajoberstar/gradle-git#275]
build.gradle file:

```groovy
plugins {
  id "com.moowork.node" version "0.12"
  id "org.ajoberstar.grgit" version "1.5.1"
}

apply plugin: 'distribution'
apply plugin: 'maven-publish'
apply plugin: 'groovy'
//apply plugin: 'org.ajoberstar.grgit'
apply from: "$rootDir/gradle/utils/repository.gradle"
apply from: "$rootDir/gradle/utils/loadPackageJson.gradle"

import org.ajoberstar.grgit.Grgit

def packageJson = loadPackageJson()

///////////////////////////////////////////////////
//                                               //
//               Project Details                 //
//                                               //
///////////////////////////////////////////////////

allprojects {
  group = 'solutions.siren'
  version = packageJson.kibi_version
}

///////////////////////////////////////////////////
//                                               //
//                    NodeJS                     //
//                                               //
///////////////////////////////////////////////////

node {
  // Version of node to use.
  version = packageJson.engines.node

  // Version of npm to use.
  npmVersion = packageJson.engines.npm

  // Base URL for fetching node distributions (change if you have a mirror).
  distBaseUrl = 'https://nodejs.org/dist'

  // If true, it will download node using above parameters.
  // If false, it will try to use globally installed node.
  download = true

  // Set the work directory for unpacking node
  workDir = file("${buildDir}/nodejs")

  // Set the work directory where node_modules should be located
  nodeModulesDir = file("${projectDir}")
}

///////////////////////////////////////////////////
//                                               //
//                  Main Tasks                   //
//                                               //
///////////////////////////////////////////////////

// Clones the local repository to generate a source artifact.
task cloneSources << {
  delete("${buildDir}/sources")
  Grgit.clone(dir: file("${buildDir}/sources"), uri: "file://${projectDir}")
}

def getBuildArgs() {
  if (project.version.endsWith("-SNAPSHOT")) {
    return ["run", "build", "--", "--release=false"]
  }
  return ["run", "build", "--", "--release=true"]
}

task npmBuildWithOpts(type: NpmTask) {
  args = getBuildArgs()
}

task build(overwrite: true, dependsOn: [npmInstall, npm_run_test, npmBuildWithOpts])
npm_run_test.mustRunAfter npmInstall
npmBuildWithOpts.mustRunAfter npm_run_test

///////////////////////////////////////////////////
//                                               //
//                Distributions                  //
//                                               //
///////////////////////////////////////////////////

distributions {

  /**
   * Distribution for the asiicdoc source of the documentation
   */
  srcDoc {
    baseName = 'investigate-doc'
    contents {
      from { "docs" }
    }
  }

  /**
   * Distribution for the investigate sources
   */
  src {
    baseName = 'investigate-core'
    contents {
      from { "${buildDir}/sources" }
    }
  }

}

///////////////////////////////////////////////////
//                                               //
//                  Publishing                   //
//                                               //
///////////////////////////////////////////////////

publishing {
  repositories getArtifactoryRepository()
  publications {

    /**
     * Core Kibi distribution
     */

    coreDist(MavenPublication) {

      /**
       * Artifacts for each platform
       */

      artifact(new File("${projectDir}/target", "investigate-${project.version}-darwin-x86_64.zip")) {
        classifier "darwin-x86_64"
      }

      artifact(new File("${projectDir}/target", "investigate-${project.version}-linux-x86_64.zip")) {
        classifier "linux-x86_64"
      }

      artifact(new File("${projectDir}/target", "investigate-${project.version}-windows-x86_64.zip")) {
        classifier "windows-x86_64"
      }

      /**
       * Source artifact
       */

      artifact srcDistZip {
        dependsOn cloneSources
        classifier "sources"
      }

      groupId project.group
      artifactId "investigate-core"
      version project.version
    }

    /**
     * Source artifact for documentation
     */

    srcDoc(MavenPublication) {
      artifact srcDocDistZip {
        classifier "sources"
      }
      groupId project.group
      artifactId "investigate-doc"
      version project.version
    }

  }
}
```

Virtual box : ubuntu-14.x
 
When I run command  `sudo gradle build --stacktrace` geting unable to resolve class org.ajoberstar.grgit.Grgit find below please help me.

```
rajasekhar@rajasekhar-VirtualBox:~/kibi$ sudo gradle build --stacktrace

FAILURE: Build failed with an exception.

* Where:
Build file '/home/rajasekhar/kibi/build.gradle' line: 13

* What went wrong:
Could not compile build file '/home/rajasekhar/kibi/build.gradle'.
> startup failed:
  build file '/home/rajasekhar/kibi/build.gradle': 13: unable to resolve class org.ajoberstar.grgit.Grgit
   @ line 13, column 1.
     import org.ajoberstar.grgit.Grgit
     ^
  
  1 error


* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.groovy.scripts.ScriptCompilationException: Could not compile build file '/home/rajasekhar/kibi/build.gradle'.
	at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler.wrapCompilationFailure(DefaultScriptCompilationHandler.java:154)
	at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler.compileScript(DefaultScriptCompilationHandler.java:120)
	at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler.compileToDir(DefaultScriptCompilationHandler.java:67)
	at org.gradle.groovy.scripts.internal.FileCacheBackedScriptClassCompiler$CacheInitializer.execute(FileCacheBackedScriptClassCompiler.java:80)
	at org.gradle.groovy.scripts.internal.FileCacheBackedScriptClassCompiler$CacheInitializer.execute(FileCacheBackedScriptClassCompiler.java:65)
	at org.gradle.cache.internal.DefaultPersistentDirectoryCache.buildCacheDir(DefaultPersistentDirectoryCache.java:100)
	at org.gradle.cache.internal.DefaultPersistentDirectoryCache.access$100(DefaultPersistentDirectoryCache.java:36)
	at org.gradle.cache.internal.DefaultPersistentDirectoryCache$1$1.run(DefaultPersistentDirectoryCache.java:82)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:165)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.writeFile(DefaultFileLockManager.java:154)
	at org.gradle.cache.internal.DefaultPersistentDirectoryCache$1.execute(DefaultPersistentDirectoryCache.java:80)
	at org.gradle.cache.internal.DefaultPersistentDirectoryCache$1.execute(DefaultPersistentDirectoryCache.java:70)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.withExclusiveLock(DefaultPersistentDirectoryStore.java:74)
	at org.gradle.cache.internal.DefaultPersistentDirectoryCache.init(DefaultPersistentDirectoryCache.java:70)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:47)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:27)
	at org.gradle.cache.internal.DefaultCacheFactory$CacheFactoryImpl.doOpenDir(DefaultCacheFactory.java:72)
	at org.gradle.cache.internal.DefaultCacheFactory$CacheFactoryImpl.open(DefaultCacheFactory.java:111)
	at org.gradle.cache.internal.DefaultCacheRepository$PersistentCacheBuilder.doOpen(DefaultCacheRepository.java:184)
	at org.gradle.cache.internal.DefaultCacheRepository$PersistentCacheBuilder.doOpen(DefaultCacheRepository.java:134)
	at org.gradle.cache.internal.DefaultCacheRepository$AbstractCacheBuilder.open(DefaultCacheRepository.java:121)
	at org.gradle.groovy.scripts.internal.FileCacheBackedScriptClassCompiler.compile(FileCacheBackedScriptClassCompiler.java:51)
	at org.gradle.groovy.scripts.internal.ShortCircuitEmptyScriptCompiler.compile(ShortCircuitEmptyScriptCompiler.java:35)
	at org.gradle.groovy.scripts.internal.CachingScriptClassCompiler.compile(CachingScriptClassCompiler.java:36)
	at org.gradle.groovy.scripts.DefaultScriptCompilerFactory$ScriptCompilerImpl.compile(DefaultScriptCompilerFactory.java:60)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:121)
	at org.gradle.configuration.BuildScriptProcessor.evaluate(BuildScriptProcessor.java:38)
	at org.gradle.configuration.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:43)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:466)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:77)
	at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:23)
	at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:21)
	at org.gradle.api.internal.Actions$CompositeAction.execute(Actions.java:78)
	at org.gradle.api.internal.Actions$TransformingActionAdapter.execute(Actions.java:130)
	at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:442)
	at org.gradle.api.internal.project.AbstractProject.allprojects(AbstractProject.java:437)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:40)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:142)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:38)
	at org.gradle.launcher.exec.InProcessGradleLauncherActionExecuter.execute(InProcessGradleLauncherActionExecuter.java:39)
	at org.gradle.launcher.exec.InProcessGradleLauncherActionExecuter.execute(InProcessGradleLauncherActionExecuter.java:25)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
	at org.gradle.api.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:48)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.Main.main(Main.java:39)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:26)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
build file '/home/rajasekhar/kibi/build.gradle': 13: unable to resolve class org.ajoberstar.grgit.Grgit
 @ line 13, column 1.
   import org.ajoberstar.grgit.Grgit
   ^

1 error

	at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler.compileScript(DefaultScriptCompilationHandler.java:118)
	... 55 more


BUILD FAILED

Total time: 5.472 secs
```

**Comment by ajoberstar** [comment]
I'm not seeing anything that looks wrong with your script. What version of Gradle are you using? (you can see this with `gradle -v`)

While I don't think it's related, you're also using a pretty old version of grgit. You could also try upgrading to [2.3.0](https://github.com/ajoberstar/grgit/releases/tag/2.3.0).

**Comment by ajoberstar** [comment]
Closing due to lack of response. Feel free to reopen, if you want to continue discussing this.
