### ISSUE TITLE
Need a dummy v0.0.0 tag to release

### ISSUE THREAD

**Issue by rspieldenner** [ajoberstar/gradle-git#77]
Using 0.11.1 when I

./gradlew release -Prelease.scope=minor -Prelease.stage=rc

It properly infers version 0.1.0 but I also get

"> No commit found for revision string: v0.0.0^{commit}"

I ended up having to create a dummy v0.0.0 tag. Is this intended? Or did I miss some configuration?

build.gradle

```
buildscript {
  repositories { jcenter() }
  dependencies {
    classpath 'org.ajoberstar:gradle-git:0.11.1'
  }
}

apply plugin: 'java'
apply plugin: 'org.ajoberstar.release-opinion'

import org.ajoberstar.grgit.Grgit

release {
  grgit = Grgit.open(project.file('.'))
}
tasks.release.dependsOn 'build'

repositories {
  jcenter()
}

dependencies {
  testCompile 'junit:junit:4.11'
}
```

**Comment by abest0** [comment]
Hey there... I reviewed the commit where this was addressed and all looks good.  However, there may be a bit of a regression with `v1.1.0-milestone.1` or something a bit more sinister.

Running the following:
``` bash
 ./gradlew release -Prelease.scope=minor -Prelease.stage=rc --stacktrace
```
Produces the error:
``` bash 
* What went wrong:
Execution failed for task ':app:release'.
> No signature of method: org.ajoberstar.grgit.Grgit.resolveCommit() is applicable for argument types: (java.lang.String) values: [v0.0.0^{commit}]

````

My `build.gradle` is as follows:
``` groovy
buildscript {
  repositories {
    jcenter()
  }

  dependencies {
    classpath 'org.ajoberstar:gradle-git:1.1.0-milestone.1'
  }
}

apply plugin: 'org.ajoberstar.release-opinion'

import org.ajoberstar.grgit.Grgit

release {
  grgit = Grgit.open(project.file('..'))
}
```

If this is a regression, then that should be a simple fix, however I think there may be something more sinister going on.

I cleared out my gradle cache `~/.gradle/caches/modules-2/files-2.1/org.ajoberstar/gradle-git` by just blowing away the whole directory.  Executing another `./gradlew release` correctly resulted in  `~/.gradle/caches/modules-2/files-2.1/org.ajoberstar/gradle-git/1.1.0-milestone.1/4a54450bec722f71623775df642b23a61dca83c4` being created.

The SHA of the directory corresponds with the SHA([4a54450bec722f71623775df642b23a61dca83c4](http://search.maven.org/#artifactdetails%7Corg.ajoberstar%7Cgradle-git%7C1.1.0-milestone.1%7Cjar)) for the jar listed in maven.org

Everything in the current repo looks good, so, I'm going to using the HEAD of master an going from there.  Just wanted to let know what was going on.

Great library, great work.

thx

**Comment by ajoberstar** [comment]
Hmm... That was definitely a regression in 1.0.0, which I thought I fixed in 1.1.0-milestone.1. I just tried reproducing the error on my device (cleaned out the ~/.gradle/caches dir even) and everything worked. Can you give me a full stack trace? Maybe this is a different error than I was thinking of. Also, if this works for you with a build from HEAD, but not from the 1.1.0-milestone.1 on JCenter, I'd be interested in that info too.

**Comment by abest0** [comment]
@ajoberstar Just to follow-up.  

I did the following:
- cloned this repo
- ran `./gradlew publishToMavenLocal`
- updated the buildscript block in the build.gradle of my test project as follows:
``` gradle
buildscript {
  repositories {
    mavenLocal()
    jcenter()
  }
...
```
- ran `./gradlew release -Prelease.scope=minor -Prelease.stage=rc` 

This **worked as expected** without having a base tag `v0.0.0` specified.

When I remove the `mavenLocal()` as a repository, gradle downloads the jar from `jcenter()` with the following stacktrace:

```
* What went wrong:                                                                                                                                                                                        Execution failed for task ':app:release'.
> No signature of method: org.ajoberstar.grgit.Grgit.resolveCommit() is applicable for argument types: (java.lang.String) values: [v0.0.0^{commit}]

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:release'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
Caused by: groovy.lang.MissingMethodException: No signature of method: org.ajoberstar.grgit.Grgit.resolveCommit() is applicable for argument types: (java.lang.String) values: [v0.0.0^{commit}]
        at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:47)
        at org.ajoberstar.grgit.Grgit.methodMissing(Grgit.groovy:174)
        at org.ajoberstar.gradle.git.release.opinion.OpinionReleasePlugin.tagExists(OpinionReleasePlugin.groovy:88)
        at org.ajoberstar.gradle.git.release.opinion.OpinionReleasePlugin.this$2$tagExists(OpinionReleasePlugin.groovy)
        at org.ajoberstar.gradle.git.release.opinion.OpinionReleasePlugin$_apply_closure1_closure2_closure3.doCall(OpinionReleasePlugin.groovy:69)
        at org.ajoberstar.gradle.git.release.base.TagStrategy.maybeCreateTag(TagStrategy.groovy:53)
        at org.ajoberstar.gradle.git.release.base.TagStrategy$maybeCreateTag.call(Unknown Source)
        at org.ajoberstar.gradle.git.release.base.BaseReleasePlugin$_addReleaseTask_closure3_closure5.doCall(BaseReleasePlugin.groovy:81)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:548)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:529)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 47 more
```

So, I'd venture to guess there may be something funky happening when publishing to bintray.

**Comment by ajoberstar** [comment]
Not sure what happened, so I'll release a 1.1.0-milestone.2 from the current HEAD to see if that helps.

**Comment by abest0** [comment]
Nice thanks! I ran a test with the new package and everything worked as expected. :beers:

**Comment by ajoberstar** [comment]
Good to hear.
